/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.4
 * Generated at: 2025-03-10 23:05:02 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.List;
import uk.ac.ucl.model.Note.Note;
import uk.ac.ucl.model.Model;
import uk.ac.ucl.model.ModelFactory;
import org.w3c.dom.Node;
import java.util.HashMap;
import java.util.Map;
import uk.ac.ucl.model.Category;

public final class notesList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(11);
    _jspx_imports_classes.add("uk.ac.ucl.model.Category");
    _jspx_imports_classes.add("uk.ac.ucl.model.Model");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("uk.ac.ucl.model.ModelFactory");
    _jspx_imports_classes.add("uk.ac.ucl.model.Note.Note");
    _jspx_imports_classes.add("org.w3c.dom.Node");
    _jspx_imports_classes.add("java.util.Map");
    _jspx_imports_classes.add("java.util.HashMap");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("  <title>Notes App</title>\n");
      out.write("  <style>\n");
      out.write("    body {\n");
      out.write("      max-width: 900px;\n");
      out.write("      margin: 0 auto;\n");
      out.write("      padding: 20px;\n");
      out.write("      font-family: 'Georgia', serif;\n");
      out.write("      background-color: #f4f1ea;\n");
      out.write("      color: #5a4d41;\n");
      out.write("    }\n");
      out.write("    h1 {\n");
      out.write("      text-align: center;\n");
      out.write("      color: #8b7d6b;\n");
      out.write("      padding-bottom: 10px;\n");
      out.write("      border-bottom: 2px solid #d9d2c9;\n");
      out.write("    }\n");
      out.write("    .controls {\n");
      out.write("      display: flex;\n");
      out.write("      justify-content: space-between;\n");
      out.write("      align-items: center;\n");
      out.write("      gap: 20px;\n");
      out.write("      margin: 20px 0;\n");
      out.write("      flex-wrap: wrap;\n");
      out.write("    }\n");
      out.write("    .filter-form, .sort-form {\n");
      out.write("      display: flex;\n");
      out.write("      align-items: center;\n");
      out.write("      gap: 10px;\n");
      out.write("    }\n");
      out.write("    .notes-table {\n");
      out.write("      border: 1px solid #d9d2c9;\n");
      out.write("      border-radius: 5px;\n");
      out.write("      overflow: hidden;\n");
      out.write("    }\n");
      out.write("    .header-row, .note-row {\n");
      out.write("      display: flex;\n");
      out.write("      padding: 12px;\n");
      out.write("      border-bottom: 1px solid #d9d2c9;\n");
      out.write("    }\n");
      out.write("    .header-row {\n");
      out.write("      font-weight: bold;\n");
      out.write("      background-color: #e6e0d4;\n");
      out.write("    }\n");
      out.write("    .note-row:last-child {\n");
      out.write("      border-bottom: none;\n");
      out.write("    }\n");
      out.write("    .note-row:hover {\n");
      out.write("      background-color: #fffcf7;\n");
      out.write("    }\n");
      out.write("    .key, .category, .label, .text, .timestamp {\n");
      out.write("      flex: 1;\n");
      out.write("      text-align: center;\n");
      out.write("      overflow: hidden;\n");
      out.write("      text-overflow: ellipsis;\n");
      out.write("      white-space: nowrap;\n");
      out.write("    }\n");
      out.write("    .key { flex: 0 0 10%; }\n");
      out.write("    .category { flex: 0 0 20%; }\n");
      out.write("    .label { flex: 0 0 25%; }\n");
      out.write("    .text { flex: 0 0 25%; }\n");
      out.write("    .timestamp { flex: 0 0 20%; }\n");
      out.write("    .note-row a {\n");
      out.write("      color: #a67f59;\n");
      out.write("      text-decoration: none;\n");
      out.write("    }\n");
      out.write("    .note-row a:hover {\n");
      out.write("      text-decoration: underline;\n");
      out.write("    }\n");
      out.write("    select, input[type=\"submit\"], .back-button {\n");
      out.write("      padding: 8px 16px;\n");
      out.write("      background-color: #a67f59;\n");
      out.write("      color: #f4f1ea;\n");
      out.write("      border: none;\n");
      out.write("      border-radius: 5px;\n");
      out.write("      font-family: 'Georgia', serif;\n");
      out.write("      cursor: pointer;\n");
      out.write("      transition: background-color 0.3s;\n");
      out.write("    }\n");
      out.write("    select:hover, input[type=\"submit\"]:hover, .back-button:hover {\n");
      out.write("      background-color: #8b7d6b;\n");
      out.write("    }\n");
      out.write("    label {\n");
      out.write("      color: #5a4d41;\n");
      out.write("      font-weight: bold;\n");
      out.write("    }\n");
      out.write("    .back-button {\n");
      out.write("      display: block;\n");
      out.write("      width: 200px;\n");
      out.write("      margin: 20px auto;\n");
      out.write("      text-attachment: center;\n");
      out.write("    }\n");
      out.write("    .no-notes {\n");
      out.write("      text-align: center;\n");
      out.write("      color: #a67f59;\n");
      out.write("      padding: 20px;\n");
      out.write("    }\n");
      out.write("  </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/header.jsp", out, false);
      out.write("\n");
      out.write("<h1>Notes</h1>\n");
      out.write("\n");
      out.write("<div class=\"controls\">\n");
      out.write("  <form action=\"/notesList.html\" method=\"get\" class=\"filter-form\">\n");
      out.write("    <label for=\"categoryFilter\">Filter by Category:</label>\n");
      out.write("    <select id=\"categoryFilter\" name=\"categoryFilter\" onchange=\"this.form.submit()\">\n");
      out.write("      <option value=\"\">All Categories</option>\n");
      out.write("      ");

        String selectedCategory = request.getParameter("categoryFilter");
        for (Category category : Category.values()) {
          String displayName = category.getDisplayName();
          String selected = displayName.equals(selectedCategory) ? "selected" : "";
      
      out.write("\n");
      out.write("      <option value=\"");
      out.print( displayName );
      out.write('"');
      out.write(' ');
      out.print( selected );
      out.write('>');
      out.print( displayName );
      out.write("</option>\n");
      out.write("      ");
 } 
      out.write("\n");
      out.write("    </select>\n");
      out.write("  </form>\n");
      out.write("\n");
      out.write("  <form action=\"/notesList.html\" method=\"get\" class=\"sort-form\">\n");
      out.write("    <label for=\"sortBy\">Sort by:</label>\n");
      out.write("    <select id=\"sortBy\" name=\"sortBy\" onchange=\"this.form.submit()\">\n");
      out.write("      <option value=\"key\" ");
      out.print( "key".equals(request.getParameter("sortBy")) ? "selected" : "" );
      out.write(">Key</option>\n");
      out.write("      <option value=\"timestamp\" ");
      out.print( "timestamp".equals(request.getParameter("sortBy")) ? "selected" : "" );
      out.write(">Timestamp</option>\n");
      out.write("      <option value=\"label\" ");
      out.print( "label".equals(request.getParameter("sortBy")) ? "selected" : "" );
      out.write(">Label</option>\n");
      out.write("      <option value=\"category\" ");
      out.print( "category".equals(request.getParameter("sortBy")) ? "selected" : "" );
      out.write(">Category</option>\n");
      out.write("    </select>\n");
      out.write("    <input type=\"hidden\" name=\"categoryFilter\" value=\"");
      out.print( selectedCategory != null ? selectedCategory : "" );
      out.write("\">\n");
      out.write("  </form>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<div class=\"notes-table\">\n");
      out.write("  <div class=\"header-row\">\n");
      out.write("    <span class=\"key\">Key</span>\n");
      out.write("    <span class=\"category\">Category</span>\n");
      out.write("    <span class=\"label\">Label</span>\n");
      out.write("    <span class=\"text\">Text</span>\n");
      out.write("    <span class=\"timestamp\">Time</span>\n");
      out.write("  </div>\n");
      out.write("  ");

    HashMap<Integer, Note> notes = (HashMap<Integer, Note>) request.getAttribute("notes");
    if (notes != null && !notes.isEmpty()) {
      for (Map.Entry<Integer, Note> entry : notes.entrySet()) {
        Note thisNote = entry.getValue();
        Integer thisKey = entry.getKey();
        String label = thisNote.getLabel();
        String text = thisNote.getText();
        String timestamp = thisNote.getTimestamp();
        Category category = thisNote.getCategory();
        String categoryDisplayName = category.getDisplayName();
        String href = "/viewNoteInfo.html?key=" + thisKey;
  
      out.write("\n");
      out.write("  <div class=\"note-row\">\n");
      out.write("    <a href=\"");
      out.print( href );
      out.write("\" class=\"key\">");
      out.print( thisKey );
      out.write("</a>\n");
      out.write("    <span class=\"category\">");
      out.print( categoryDisplayName );
      out.write("</span>\n");
      out.write("    <span class=\"label\">");
      out.print( label.length() > 25 ? label.substring(0, 25) + "..." : label );
      out.write("</span>\n");
      out.write("    <span class=\"text\">");
      out.print( text.length() > 25 ? text.substring(0, 25) + "..." : text );
      out.write("</span>\n");
      out.write("    <span class=\"timestamp\">");
      out.print( timestamp.substring(5, 16) );
      out.write("</span>\n");
      out.write("  </div>\n");
      out.write("  ");

    }
  } else {
  
      out.write("\n");
      out.write("  <div class=\"no-notes\">No notes available.</div>\n");
      out.write("  ");

    }
  
      out.write("\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<button class=\"back-button\" onclick=\"window.location.href='http://localhost:8080'\">Back to Home</button>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
